name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests with Allure
      run: npx playwright test --reporter=line,allure-playwright

    - name: Generate Allure Report
      run: |
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
        tar -xvzf allure-2.27.0.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        allure generate ./allure-results --clean -o ./allure-report

    - name: Upload Allure report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: ./allure-report

    - name: Upload Playwright HTML report
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30